#!/usr/bin/ruby

require 'nokogiri'

if ARGV.empty?
    STDERR.puts File.basename("#{$PROGRAM_NAME}") \
                              + ": Directory argument missing."
    exit 1
end

path = "#{ARGV[0]}"

Dir.glob(path + "/**/*.html").each do |html_file|
    doc = File.open(html_file) { |f| Nokogiri::HTML(f) }
    doc.xpath('//meta').remove
    doc.xpath('//script').remove_attr("type")
    doc.xpath('//form[@action=""]').remove_attr("action")
    doc.xpath('//table').remove_attr("border")
    doc.xpath('//table').remove_attr("class")
    doc.xpath('//table/thead').remove_attr("valign")
    doc.xpath('//table/tbody').remove_attr("valign")
    doc.xpath('//table/colgroup').remove
    doc.xpath('//input').remove_attr("autocorrect")

    doc.xpath('//a[starts-with(@href, "mailto:ssh")]').each do |anchor|
        anchor.replace anchor.children
    end

    doc.xpath('//a[starts-with(@href, "mailto:debian")]').each do |anchor|
        anchor.replace anchor.children
    end

    doc.xpath('//a[starts-with(@href, "about:")]').each do |anchor|
        anchor.replace anchor.attr('href')
    end

    generator_mention_children \
        = doc.xpath('//div[@class="footer" and @role="contentinfo"]' \
                    '/div[@class="generator_mention"]').children[0, 3]
    doc.xpath('//div[@class="footer" and @role="contentinfo"]' \
              '/div[@class="generator_mention"]').children[3...].remove
    generator_mention_children.first.replace \
        "Static website built using "
    generator_mention_children.last.replace \
        " and <a href=\"https://nokogiri.org/\">Nokogiri</a>. Validated " \
        "<a href=\"https://validator.w3.org/check?uri=referer\">HTML5</a> / " \
        "<a href=\"https://jigsaw.w3.org/css-validator/check/referer\">CSS3" \
        "</a>."

    footer_children \
        = doc.xpath('//div[@class="footer" and @role="contentinfo"]').children
    footer_children_first=footer_children.first.to_s.sub(" Thierry Rascle", \
        " <a class=\"reference internal\" href=\"about.html\">"\
        "<span class=\"doc\">"\
        "Thierry Rascle"\
        "</span></a>")
    footer_children.first.replace footer_children_first

    doc.write_html_to(File.new(html_file, 'w'), :encoding => 'UTF-8')
end
